<a href="https://colab.research.google.com/github/mathewalex262006/ict/blob/main/internship2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for num in range(5):
  print (num)

0
1
2
3
4


In [ ]:
for num in range(1,20):
  print (num)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
for i in range (5):
  print ("welcom all")


welcom all
welcom all
welcom all
welcom all
welcom all


In [ ]:
grocery_list = ["apple","banana","milk","egg","yogurt","bread"]
print("item to buy:")
for item in grocery_list:
  print(item)

item to buy:
apple
banana
milk
egg
yogurt
bread


In [ ]:
grocery_list = ["apple","banana","milk","egg","yogurt","bread"]

new_list = ["juice","pencil box","cheese","eggs","milk","pens"]

for item in new_list:
  if item in grocery_list:
    print(f"{item} already in the list")
  else:
    grocery_list.append(item)
    print(f"{item} add to the list")

print("updated grocery list:")
print(grocery_list)




juice add to the list
pencil box add to the list
cheese add to the list
eggs add to the list
milk already in the list
pens add to the list
updated grocery list:
['apple', 'banana', 'milk', 'egg', 'yogurt', 'bread', 'juice', 'pencil box', 'cheese', 'eggs', 'pens']


In [ ]:
expenses = [400,590,490,700,560,300,900,450]
total = 0
for expense in expenses:
  total += expense
print(total)

4390


In [ ]:
numbers = ["7875380656","67456890","7654397857","787564327","876548764"]
for number in numbers:
  if len(number) == 10:
    print("number")
  else:
     print("invalid number")

number
invalid number
number
invalid number
invalid number


In [ ]:
count = 1
while count < 10:
  print(f"counting {count}")
  count += 1

print("loop completed")



counting 1
counting 2
counting 3
counting 4
counting 5
counting 6
counting 7
counting 8
counting 9
loop completed


In [ ]:
amount = int(input("enter your saving amount"))
total=0

while amount != 0:
  total += amount
  amount = int(input("enter the amount to be saved"))

print("total is",total)

enter your saving amount468
enter the amount to be saved6987
enter the amount to be saved0
total is 7455


In [ ]:
cart = {"shoese":2000,"bag":3500,"watch":2000,"glasses":1200}
for item,price in cart.items():
  if price > 2000:
    print(f"this {item} is costly")
  else:
    print(f"{item} can be purchased")

shoese can be purchased
this bag is costly
watch can be purchased
glasses can be purchased


In [ ]:
cart = {"shoese":2000,"bag":3500,"watch":2000,"glasses":1200}
for item in cart.keys():
  if cart[item] > 2000:
    print(f"this {item} is costly")
  else:
    print(f"{item} can be purchased")

shoese can be purchased
this bag is costly
watch can be purchased
glasses can be purchased


In [ ]:
def greet():
  print("hi , welcom to the seassion")

In [ ]:
greet()


hi , welcom to the seassion


In [ ]:
def greet(name):
  print("hi {name}, welcom to the seassion")


greet ("maya")
greet ("johny")


hi {name}, welcom to the seassion
hi {name}, welcom to the seassion


In [ ]:
def send_gift(recipient,gift):
  print(f"sending {gift} to {recipient}")

send_gift("maya","iphone")
send_gift("midhuna","a bag")
send_gift("balu","a shirt")

sending iphone to maya
sending a bag to midhuna
sending a shirt to balu


In [ ]:
def send_gift(recipient):
  print(f"sending  gift to {recipient}")

send_gift("maya")
send_gift("midhuna")
send_gift("balu")

sending  gift to maya
sending  gift to midhuna
sending  gift to balu


In [ ]:
def send_gift(recipient,gift="roses"):
  print(f"sending {gift} to {recipient}")

send_gift("maya","iphone")
send_gift("midhuna","a bag")
send_gift("balu","a shirt")

sending iphone to maya
sending a bag to midhuna
sending a shirt to balu


In [ ]:
def add_ten(number):
  return (number+10)

add_ten(5) * 2

30

In [ ]:
def calculate_total_bill(item_prices):
  platform_fee = 5
  delivery_charge = 80
  subtotal = sum(item_prices)
  subtotal += platform_fee
  subtotal += delivery_charge
  return subtotal

item_prices = {100,200,300,400}
subtotal = calculate_total_bill(item_prices)
if subtotal > 1000:
  reward= 200
elif subtotal >500:
  reward= 50
else:
  reward = 0
print(f"your subtotal is {subtotal} and reward is {reward}")


your subtotal is 1085 and reward is 200


In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [ ]:
y = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
)
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
y.shape

(4, 3)

In [ ]:
y.ndim

2

In [ ]:
np.random.randint(1,50,size=(4,3))

array([[ 5, 12, 45],
       [31, 43, 41],
       [26, 29,  3],
       [23, 27, 34]])

In [ ]:
x = np.array([0,1,2,3,4])
y = np.array([5.5,-6.5,-4,7.5,8])

np.add(x,y)

array([ 5.5, -5.5, -2. , 10.5, 12. ])

In [ ]:
x = np.array([0,1,2,3,4])
y = np.array([5.5,-6.5,-4,7.5,8])

np.subtract(x,y)

array([-5.5,  7.5,  6. , -4.5, -4. ])

In [ ]:
x = np.array([0,1,2,3,4])
y = np.array([5.5,-6.5,-4,7.5,8])

np.multiply(x,y)

array([ 0. , -6.5, -8. , 22.5, 32. ])

In [ ]:
x = np.array([0,1,2,3,4])
y = np.array([5.5,-6.5,-4,7.5,8])

np.divide(x,y)

array([ 0.        , -0.15384615, -0.5       ,  0.4       ,  0.5       ])

In [ ]:
import pandas as pd
data = pd.read_csv("/content/pandas-practice-data.csv")
data.head(10)


,Duration,Pulse,Maxpulse,Calories
0,60,110,130,409.1
1,60,117,145,479.0
2,60,103,135,340.0
3,45,109,175,282.4
4,45,117,148,406.0
5,60,102,127,300.0
6,60,110,136,374.0
7,45,104,134,253.3
8,30,109,133,195.1
9,60,98,124,269.0


In [ ]:
import pandas as pd
data = pd.read_csv("/content/pandas-practice-data.csv")
data.tail()

,Duration,Pulse,Maxpulse,Calories
164,60,105,140,290.8
165,60,110,145,300.0
166,60,115,145,310.2
167,75,120,150,320.4
168,75,125,150,330.4


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
data.describe()

,Duration,Pulse,Maxpulse,Calories
count,169.000000,169.000000,169.000000,164.000000
mean,63.846154,107.461538,134.047337,375.790244
std,42.299949,14.510259,16.450434,266.379919
min,15.000000,80.000000,100.000000,50.300000
25%,45.000000,100.000000,124.000000,250.925000
50%,60.000000,105.000000,131.000000,318.600000
75%,60.000000,111.000000,141.000000,387.600000
max,300.000000,159.000000,184.000000,1860.400000


In [ ]:
data.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
data["Duration"]

,Duration
0,60
1,60
2,60
3,45
4,45
...,...
164,60
165,60
166,60
167,75


In [ ]:
data["Duration"].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [ ]:
data["Duration"].value_counts()

,count
Duration,
60,79
45,35
30,16
20,9
90,8
150,4
180,3
120,3
75,2


In [ ]:
data.isna().sum()

,0
Duration,0
Pulse,0
Maxpulse,0
Calories,5


In [ ]:
new_data = data.dropna()
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  164 non-null    int64  
 1   Pulse     164 non-null    int64  
 2   Maxpulse  164 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB


In [ ]:
cal_mean = data["Calories"].mean()
data["Calories"] = data["Calories"].fillna(cal_mean)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
data["caloriesPerMinute"] = data["Calories"]/data["Duration"]
data

,Duration,Pulse,Calories,caloriesPerMinute
0,60,110,409.1,6.818333
1,60,117,479.0,7.983333
2,60,103,340.0,5.666667
3,45,109,282.4,6.275556
4,45,117,406.0,9.022222
...,...,...,...,...
164,60,105,290.8,4.846667
165,60,110,300.0,5.000000
166,60,115,310.2,5.170000
167,75,120,320.4,4.272000


In [ ]:
data.drop("Maxpulse",axis=1,inplace=True)

In [ ]:
data.head()

,Duration,Pulse,Calories
0,60,110,409.1
1,60,117,479.0
2,60,103,340.0
3,45,109,282.4
4,45,117,406.0


In [ ]:
import pandas as pd
data = pd.read_csv("/content/titanic_dataset.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [ ]:
import pandas as pd
data = pd.read_csv("/content/titanic_dataset.csv")
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data["Fare"]

,Fare
0,7.2500
1,71.2833
2,7.9250
3,53.1000
4,8.0500
...,...
886,13.0000
887,30.0000
888,23.4500
889,30.0000


In [ ]:
data["Fare"].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [ ]:
data["Fare"].value_counts()

,count
Fare,
8.0500,43
13.0000,42
7.8958,38
7.7500,34
26.0000,31
...,...
13.8583,1
50.4958,1
5.0000,1


In [ ]:
data.isna().sum()

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [ ]:
new_data = data.dropna()
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    object 
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB


In [ ]:
cal_mean = data["Age"].mean()
data["Age"] = data["Age"].fillna(cal_mean)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
